---

- name: Create user groups
  group: 
    name: "{{item}}"
    state: present
  with_items: user_groups

- name: Create user
  user: 
    name: "{{sdk_user}}" 
    shell: /bin/bash
    
- name: Add sdk_user to groups
  user:
    name: "{{sdk_user}}"
    groups: "{{item}}"
    append: yes
    state: present
  with_items: user_groups

- name: Download prereqs
  get_url: 
    url: "{{item.download.url}}"
    dest: "{{item.download.dest}}"
    mode: "{{item.download.mode}}"
    owner: "{{sdk_user}}"
    group: developers
    force: yes
    validate_certs: yes
  with_items: prereqs_files

- name: Execute prereqs as sdk user
  command: bash {{item.download.dest}}
  with_items: prereqs_files
  sudo_user: "{{sdk_user}}"

# Need a 'exists' grep to prevent doing this again
- name: Modify bashrc for user
  lineinfile:
    dest: /home/{{sdk_user}}/.bashrc
    backup: yes
    line: "{{item}}"
    owner: "{{sdk_user}}"
    regexp: ''
    state: present
    insertafter: EOF
    create: True
  with_items: bashrc_updates
  sudo_user: "{{sdk_user}}"

- name: Download Install files
  get_url: 
    url: "{{item.download.url}}"
    dest: "{{item.download.dest}}"
    mode: "{{item.download.mode}}"
    owner: "{{sdk_user}}"
    group: developers
    force: yes
    validate_certs: yes
  with_items: install_files

# Templates
- name: Generate templates
  template: 
    src: "{{item.file.src}}"
    dest: "{{item.file.dest}}"
    owner: "{{item.file.owner}}"
    group: "{{item.file.group}}"
    mode: "{{item.file.mode}}"
  with_items: templates

- name: Execute post install script
  shell: . ~/.bashrc && /home/{{sdk_user}}/post_install.sh
  args:
    executable: /bin/bash
  sudo_user: "{{sdk_user}}"
  async: 3000
  poll: 120

