---
#
# Test Playbook
#

- hosts: localhost
  connection: local

  roles:
    # - { 
    #     role: jhthorsen.perlbrew, 
    #     perlbrew_user: ddghacker, 
    #     perlbrew_root: /home/ddghacker/perl5/perlbrew,
    #     user: ddghacker, 
    #     perl_version: perl-5.20.1,
    #     sudo: yes
    # }
    - { role: ../../, sudo: yes }

# - include: tests.yml
