---

- hosts: localhost
  connection: local
  sudo: yes
  
  tasks:
    # Sample Test - tests for uname
    - name: Display uname
      command: uname
      register: host_os

    - fail:
        msg: "Sample test failed"
      when: host_os.rc != 0

    - name: Check for Perlbrew
      stat: path=/home/ddghacker/perl5/perlbrew/bin/perlbrew
      register: path_perlbrew

    - fail: msg="Perlbrew not found for user ddghacker!"
      when: path_perlbrew.stat.exists == false

    # We know this playbook installs one
    - name: List installed perl
      shell: "source /home/ddghacker/.bashrc && /home/ddghacker/perl5/perlbrew/bin/perlbrew list | sed -e 's/^[[:space:]]*//'"
      args:
        executable: /bin/bash
      sudo_user: ddghacker
      register: installed_perl

    - fail:
        msg: "Perlbrew not installed correctly"
      when: installed_perl.stdout != "perl-5.16.3"

    - debug:
        msg: "Tests pass for this [{{host_os.stdout}}] box."
